branch_protection_rules:
  - pattern: main
    required_status_checks:
      strict: true
      contexts:
        - build
    enforce_admins: true
    required_pull_request_reviews:
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
      required_approving_review_count: 1
    restrictions:
      users:
        - tin-machine
