name: Go Build

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: darwin
            goarch: amd64

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'

    - name: Get dependencies
      run: go mod download

    - name: Set Version
      run: |
        if [ "${{ github.ref_type }}" = "tag" ]; then
          echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
        else
          echo "VERSION=${{ github.sha }}" >> $GITHUB_ENV
        fi
        echo "Version is ${{ env.VERSION }}"

    - name: Build
      run: |
        echo "Building for ${{ matrix.goos }}/${{ matrix.goarch }}"
        mkdir -p build
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags="-X main.Version=${{ env.VERSION }}" -v -o build/gpt-cli-${{ matrix.goos }}-${{ matrix.goarch }} ./...
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gpt-cli-${{ matrix.goos }}-${{ matrix.goarch }}
        path: build/gpt-cli-${{ matrix.goos }}-${{ matrix.goarch }}
  release:
    name: release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: build
    env:
      VERSION: ${{ github.ref_name }}
    permissions:
      contents: write
    steps:
      - run: |
          gh release create "${VERSION}" --title "${VERSION}" --generate-notes
          gh release upload "${VERSION}" "build/*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



#      - name: Download all artifacts
#        uses: actions/download-artifact@v4
#        with:
#          path: build
#      - name: List build directory
#        run: ls -la build
#      - name: リリース作成
#        uses: softprops/action-gh-release@v1
#        with:
#          tag_name: ${{ github.event.pull_request.title }}
#          name: ${{ github.event.pull_request.body }}
#          generate_release_notes: true
#          files: build/*
