name: Go Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go mod download

    - name: Build
      run: |
        echo "Building for ${{ matrix.goos }}"
        GOOS=${{ matrix.goos }} GOARCH=amd64 go build -v -o myapp-${{ matrix.goos }} ./...

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: myapp-${{ matrix.goos }}
        path: ./myapp-${{ matrix.goos }}
