name: Pull Request Checks

on:
  pull_request:
    branches:
      - main

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version-file: './go.mod'  # go.modからバージョンを取得

      # Lintチェック
      - name: Install golint
        run: go install golang.org/x/lint/golint@latest
        echo "$HOME/go/bin" >> $GITHUB_PATH  # golintのパスを追加

      - name: Run golint
        run: golint ./...  # プロジェクト全体をLintチェック

      - name: Run gofmt
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "Please format your Go code with 'gofmt'."
            gofmt -d .  # フォーマットの差分を表示
            exit 1
          fi

      # テスト実行
      - name: Run Tests
        run: go test -v ./...  # 全テストを実行し、詳細な出力を表示
